### ISSUE TITLE
get-pip HTTSHandler import error

### ISSUE THREAD

**Issue by maedoc** [nwhitehead/pineapple#60]
On CentOS 7 (64-bit Linux), `cmake .. && make` went fine, but `make custom-install` leads to a failure to import HTTPSHandler, 
```
~/Downloads/pineapple/build make custom-install
[  0%] Built target custom-reinstall-first
[  0%] Built target compile-less
[  0%] Built target custom-reinstall
[ 24%] Built target openssl-external
[ 24%] Built target openssl
[ 48%] Built target python3.5-external
[ 48%] Built target python3.5
[ 72%] Built target libcurl-external
[ 72%] Built target libcurl
[ 96%] Built target pycurl-external
[ 96%] Built target pycurl
[100%] Setting up pip
Traceback (most recent call last):
  File "/home/mw/Downloads/pineapple/external/python-3.5/get-pip.py", line 17759, in <module>
    main()
  File "/home/mw/Downloads/pineapple/external/python-3.5/get-pip.py", line 162, in main
    bootstrap(tmpdir=tmpdir)
  File "/home/mw/Downloads/pineapple/external/python-3.5/get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmp4ggr3xpu/pip.zip/pip/__init__.py", line 15, in <module>
  File "/tmp/tmp4ggr3xpu/pip.zip/pip/vcs/subversion.py", line 9, in <module>
  File "/tmp/tmp4ggr3xpu/pip.zip/pip/index.py", line 30, in <module>
  File "/tmp/tmp4ggr3xpu/pip.zip/pip/wheel.py", line 35, in <module>
  File "/tmp/tmp4ggr3xpu/pip.zip/pip/_vendor/distlib/scripts.py", line 14, in <module>
  File "/tmp/tmp4ggr3xpu/pip.zip/pip/_vendor/distlib/compat.py", line 66, in <module>
ImportError: cannot import name 'HTTPSHandler'
make[3]: *** [CMakeFiles/python3.5-postinstall] Error 1
make[2]: *** [CMakeFiles/python3.5-postinstall.dir/all] Error 2
make[1]: *** [CMakeFiles/custom-install.dir/rule] Error 2
make: *** [custom-install] Error 2
```
It seems that the Python 3.5 build isn't picking up on the custom SSL build. I tried to dig into it myself, but the combination of CMake & [rather complex advice on configuring Python with custom SSL](http://stackoverflow.com/questions/5937337/building-python-with-ssl-support-in-non-standard-location) exceeds my time limit for today.

I'd love to help with Linux & Windows builds, though, so any pointers here are welcome.

**Comment by maedoc** [comment]
For what it's worth, I continued with some workarounds, 

- `cd`ing into the Python src 
- `./configure --prefix=$(pwd)/../../python-3.5 && make && make install`
- change git numpy to 1.9.2 in the requirements
- `make custom-install`
